### PR TITLE
Check whether the passphrase prompt action completed successfully.

### LINKED ISSUE #80: Passphrase dialog hides after entering incorrect passphrase
This is due to the action catching the error and simply returning from the function, as if it was successful.

### PR DESCRIPTION
**Pull request by jrick**
Change the function signature of the passed delegate to return a bool.
When true, the dialog hides.  This allows the delegate to perform
error handling and return early without the dialog automatically
hiding.

Fixes #80.

### CODE REVIEW

File: Paymetheus/ViewModels/PassphraseDialogViewModel.cs [hunk 1]
```diff
@@ -33,8 +33,9 @@ public PassphraseDialogViewModel(ShellViewModel shell, string header, string but
         {
             try
             {
-                await _execute(Passphrase);
-                HideDialog();
+                var success = await _execute(Passphrase);
```
Comment (marcopeereboom) [inline Paymetheus/ViewModels/PassphraseDialogViewModel.cs:36]: why declare a var?  cant you just do if (await _execute()) ?

Comment (jrick) [inline Paymetheus/ViewModels/PassphraseDialogViewModel.cs:36]: yes, that's possible too.  i just gave it a name since the function sig isn't documented anywhere (i should probably make it a named delegate type, and give it a doco comment) so it should be obvious if true or false means success or not.

**Comment by marcopeereboom** [comment]
tOK
